apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-cr
rules:
- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "update"]

- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list"]

- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list"]
  