apiVersion: v1
kind: Pod
metadata:
  name: "nginx-distroless"
  namespace: default
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
  - name: nginx-distroless 
    image: kyos0109/nginx-distroless
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 80
      name: http
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_PTRACE", "SYS_ADMIN"]
      allowPrivilegeEscalation: true
      seccompProfile:
        type: Unconfined
  restartPolicy: Always