apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMU1ETXhNVEE0TkRnME4xb1hEVEk0TURNeE1UQTRORGcwTjFvd01URVhNQlVHQTFVRQpDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGakFVQmdOVkJBTVREVzFwYm1scmRXSmxMWFZ6WlhJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDYlVWb1RWTk5RaDdBTDFsRUh2eDVMcjhnMndUMHAKMDROSXpTUXVITG5FWUpRUmozdlBHV0xGYml3WUFUUkwzdU5VTmx6dkR1N0tvanVRZTg3Z0JhZDQzRmx1Y0J2VAp3WEgreEoySTZMN0JoQWFjZkZKNFBrL2RlS3NZWWl5KzBoVGhFRjNXcEZ1VzRPcW1BaGVCVFNVZTMrT0FadWN3CjJXZHBWVStueDgxZDRsekZEOGMzQml6eXRTM1ozUlRXUFN6alNybnhxWUl2T2hOcjZiNjJhSjlQSmk1dUFZaTkKOFUrSzRCODVabWhyenVBc0Vlb1FzSHNKSU9DZ2w4Ykk0R0F6MkY0Tk42T1ZIcWhNWDlGbHBvT05UOU1nOHpmaQo3dVo3WTR3OVBSU01TeWcySytEOG9qVEpiZ2dhZkpkUFY5U21id3d4UUdGMUM1eWlaYXRYNzNyVkFnTUJBQUdqCllEQmVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSRU1LeE5PQ2ZOOVpYSytabkpCWGJGdGFscwpOREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUk92WEdOUHZOYythRWJVaGtZdHVPaGtuUXd6ZTc2Zm03V21NCllCeXlabElSMHdkbjNKcXBOeUQzeUpQUmZOOTVYZ2x2am84OVdWbVZvay9LL0QyaDh4Z3AvQmNzczdMVGNuWDQKV08wTVg0VEQ5Y3cvL2dQR2hSclRHVVp4V0pSaTF5N3BXRnhiWnJzYjI1RzhTSG1yRDZvUUZwZHNId2hOV1ppYgpkNTVhbnhqbVdsRjBTU0d4SW94aHNrb2Z1STUxL3dOcHMwUkpTOEg2NGYzWUhod0lWK0xUdzVpM2dQUGZTQXF2Cm5CeFYvVWpDbU5TUW9HOXFyei9aRjRRazhxam81VTR6Z1lBY3hNMFo2TnNXTENqdW90bnBlUGt2QTkxUlk4azgKMDRoeDJKZGRXTHJVaDVTa0k1dEQ1Z3dEeUQ2eDhmcDZUUnlvUW5lNG1NQXMvZE5EOGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    extensions:
    - extension:
        last-update: Thu, 17 Apr 2025 21:13:47 MSK
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: cluster_info
    server: https://127.0.0.1:50836
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkxGM1czN0hqTFdmZ1dDaXVQR2o3MWg2Y0E2c2s1aVdRZ3M5UWNOMW41QVEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ1MDUwNzI2LCJpYXQiOjE3NDQ5NjQzMjYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiOGZmYTM0YTctYWE1Ni00ZGM1LTg5MTktNTc2NDBmZTNjMmQ4Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6ImU2ZmRkZGQyLTkyZDctNDA3OC1hZDA3LWEwZTVlNDJkMzgzZSJ9fSwibmJmIjoxNzQ0OTY0MzI2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.gSYlReuuLYEp_KQI07HZIttEFob7PpHUOdvQcDjn_3risV85ajJ3hrUst3M23VjUfOlY0Rw6jNjo_It_zjX4xfJT6KJwgZMxjSflQl5YkcRiqz69KYber2uY0sGNjUJFU1f8Ly_0DuvSPI_g5rDKa68ufTlwiEZM-R3SzeEq1U8Mg3CtL5ptbIwsQ5m3DXek6oVA65azoZqQp9VCjtbVsq0JPOLdaAFkBUglq91TE_SEFMUtWvw76AL1B34NVzGFxgCPpSg6NwcUbiDA3eOXFUUoKWMVGBZ8g0ESJn1eKGcZ39as7HzmpC1Qclb1KtCkS4pZT4a7CbbpVopVMT6WcQ