apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-monitoring
subjects:
- kind: ServiceAccount
  name: monitoring
  apiGroup: ""
  namespace: homework
roleRef:
  kind: ClusterRole
  name: metrics-access
  apiGroup: rbac.authorization.k8s.io
  