repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # PROD кластер Kafka
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: 23.0.8
    values:
      - image:
          tag: 3.5.2-debian-11-r0
        replicaCount: 5
        auth:
          clientProtocol: sasl
          interBrokerProtocol: sasl
          saslMechanisms: plain
          saslAllowedMechanisms: plain
          interBrokerUser: admin
          interBrokerPassword: "adminpass"
          deleteTopicEnable: true

  # DEV кластер Kafka
  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    version: 23.0.8
    values:
      - replicaCount: 1
        auth:
          clientProtocol: plaintext
          interBrokerProtocol: plaintext
          allowPlaintextListener: true
          deleteTopicEnable: true