---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: otus
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      namespace: "vault"
      path: "otus"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          serviceAccountRef:
            name: "vault-auth"