apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webserver.fullname" . }}-ingress
  namespace: {{ .Values.global.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "webserver.fullname" . }}-service
                port:
                  number: {{ .Values.service.ports.port }}
          - path: /homepage
            pathType: Prefix
            backend:
              service:
                name: {{ include "webserver.fullname" . }}-service
                port:
                  number: {{ .Values.service.ports.port }}
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "webserver.fullname" . }}-service
                port:
                  number: {{ .Values.service.ports.port }}