apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name}}
  namespace: {{ .Values.global.namespace}}
spec:
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  accessModes:
    - {{ .Values.pvc.accessModes }}
  storageClassName: {{ .Values.storageClass.name }}