apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.fullname" . }}-service
  namespace: {{ .Values.global.namespace}}
spec:
  selector:
    app: {{ include "webserver.fullname" . }}-deployment
  ports:
  - port: {{ .Values.service.ports.port}}
    targetPort: {{ .Values.service.ports.targetPort}}
  type: {{ .Values.service.type }}