deploymentMode: SingleBinary

global:
  serviceaccountawskeyvalue: |
    {
      "access_key": {
        "key_id": ""
      },
      "secret": ""
    }
  bucketname: <>

promtail:
    tolerations:
        - key: "node-role"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2025-03-13"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

  ruler:
    enable_api: true

  nodeSelector:
    node-role: "infra"

  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role
                operator: In
                values:
                  - infra

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

singleBinary:
  replicas: 1

chunksCache:
  enabled: true
  allocatedMemory: 1024
  nodeSelector:
    node-role: "infra"
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role
                operator: In
                values:
                  - infra
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

minio:
  enabled: false